Assignment2
nikhil1-successive/React-training pull request #2
Opened 2023-11-01 04:06 UTC by nikhil1-successive

2023-11-02 10:05 UTC, shahbaz-successive commented on assignment-2/src/Questions/Ques2/PersonForm.jsx
> +        type="age"
type should be number

2023-11-02 10:08 UTC, shahbaz-successive commented on assignment-2/src/Questions/Ques5/Counterwithstep.jsx
> +      <button onClick={() => setcnt(cnt + parseInt(step))}>Increment</button>
Why parseInt is used here? Explain

2023-11-02 10:25 UTC, shahbaz-successive commented on assignment-2/src/Questions/Ques9/ThemeSwitcher.jsx
> +    <ThemeContext.Provider value={theme}>
You should not wrap the children here. Please see createContext proper use  and update code. You can create context in another file and import it.

2023-11-02 10:26 UTC, shahbaz-successive commented on assignment-2/src/Questions/Ques10/LanguageSwitcher.jsx
> +      <LanguageSwitcher2 />
You should not wrap the LanguageSwitcher2 here. Please see createContext proper use and update code. You can create context in another file and import it.

2023-11-02 11:02 UTC, shahbaz-successive commented on assignment-2/src/Questions/Ques11/ShoppingCart.jsx
> +  const { cartState, dispatch } = useContext(CartContext);
Remove cartState as it is not being used

2023-11-02 11:13 UTC, shahbaz-successive commented on assignment-2/src/Questions/ques16/EmployeeSalary.jsx
> +      <button onClick={updateSalaries}>Update Salaries</button>
Update button should update all employee salary randomly instead of providing an Input

2023-11-02 11:25 UTC, shahbaz-successive commented on assignment-2/src/Questions/ques18/UseLocalStorage.jsx
> +        onChange={(e) => setName(e.target.value)}
In local storage value is not being saved as key-value pair. Please check and update

2023-11-02 11:26 UTC, shahbaz-successive requested changes
Please do feedback changes

2023-11-02 16:41 UTC, nikhil1-successive commented on assignment-2/src/Questions/Ques5/Counterwithstep.jsx
> +function Counterwithstep() {
done

2023-11-02 16:42 UTC, nikhil1-successive commented on assignment-2/src/Questions/Ques5/Counterwithstep.jsx
> +      <button onClick={() => setcnt(cnt + parseInt(step))}>Increment</button>
because step is string so we need to parse int it.

2023-11-03 06:41 UTC, nikhil1-successive commented on assignment-2/src/Questions/Ques5/Counterwithstep.jsx
> +      <button onClick={() => setcnt(cnt + parseInt(step))}>Increment</button>
now am using type conversion string to number here in this handleNumber function to avoid using parseInt with button on click.
 const handleNumber = (event) => {
    setStep(Number(event.target.value));
  };

2023-11-03 10:34 UTC, nikhil1-successive commented on assignment-2/src/Questions/ques18/UseLocalStorage.jsx
> +        onChange={(e) => setName(e.target.value)}
Now Storing value directly

2023-11-03 10:34 UTC, nikhil1-successive commented on assignment-2/src/Questions/ques16/EmployeeSalary.jsx
> +      <button onClick={updateSalaries}>Update Salaries</button>
Done

2023-11-03 10:34 UTC, nikhil1-successive commented on assignment-2/src/Questions/Ques11/ShoppingCart.jsx
> +  const { cartState, dispatch } = useContext(CartContext);
Done

2023-11-03 10:34 UTC, nikhil1-successive commented on assignment-2/src/Questions/Ques11/ShoppingCart.jsx
> +const cartReducer = (state, action) => {
Now working

2023-11-06 05:03 UTC, shahbaz-successive approved these changes
👍

2023-11-06 05:03 UTC, merged