assignment-4
nikhil1-successive/React-training pull request #4
Opened 2023-11-09 06:13 UTC by nikhil1-successive

2023-11-09 07:00 UTC, shahbaz-successive commented on src/assignment-4/Ques4/Ques4jsx.jsx
> +  const [msg, setMsg] = useState("")
Remove this used code

2023-11-09 07:00 UTC, shahbaz-successive commented on src/assignment-4/Ques4/Ques4jsx.jsx
> +  const [passwordsMatch, setPasswordsMatch] = useState(true);
Remove this unused useState

2023-11-09 07:01 UTC, shahbaz-successive commented on src/assignment-4/Ques4/Ques4jsx.jsx
> +        {/* {!passwordsMatch && (
Remove this comment

2023-11-09 07:53 UTC, nikhil1-successive commented on src/assignment-4/Ques4/Ques4jsx.jsx
> +  const [msg, setMsg] = useState("")
done

2023-11-09 07:53 UTC, nikhil1-successive commented on src/assignment-4/Ques4/Ques4jsx.jsx
> +  const [passwordsMatch, setPasswordsMatch] = useState(true);
done

2023-11-09 07:54 UTC, nikhil1-successive commented on src/assignment-4/Ques4/Ques4jsx.jsx
> +        {/* {!passwordsMatch && (
done

2023-11-13 01:03 UTC, shahbaz-successive commented on src/assignment-4/Ques7/Ques7jsx.jsx
> +  const [items, setItems] = useState(["Apple", "Kiwi", "Litchi"]);
If not use setItems, just define it in an array instead of useState

2023-11-13 01:16 UTC, shahbaz-successive commented on src/assignment-4/Ques14/Ques14jsx.jsx
> +  return (
Create form using Material UI

2023-11-13 01:17 UTC, shahbaz-successive requested changes
Feedback changes

2023-11-13 01:21 UTC, shahbaz-successive commented on src/assignment-4/Ques4/Ques4jsx.jsx
> +    } else if (formData.password != "") {
Use strict check !==

2023-11-13 01:21 UTC, shahbaz-successive commented on src/assignment-4/Ques4/Ques4jsx.jsx
> +    if (formData.password != "" && formData.password === formData.confirmPassword) {
Use strict check !==

2023-11-13 01:21 UTC, shahbaz-successive requested changes
Feedbacks

2023-11-13 05:46 UTC, nikhil1-successive commented on src/assignment-4/Ques4/Ques4jsx.jsx
> +    if (formData.password != "" && formData.password === formData.confirmPassword) {
done

2023-11-13 05:47 UTC, nikhil1-successive commented on src/assignment-4/Ques4/Ques4jsx.jsx
> +    } else if (formData.password != "") {
done

2023-11-13 05:47 UTC, nikhil1-successive commented on src/assignment-4/Ques7/Ques7jsx.jsx
> +  const [items, setItems] = useState(["Apple", "Kiwi", "Litchi"]);
done

2023-11-13 06:04 UTC, nikhil1-successive commented on src/assignment-4/Ques14/Ques14jsx.jsx
> +  return (
done

2023-11-13 11:05 UTC, shahbaz-successive approved these changes
👍

2023-11-13 11:05 UTC, merged