Feature/assignment 6
nikhil1-successive/React-training pull request #6
Opened 2023-11-12 16:58 UTC by nikhil1-successive

2023-11-13 02:12 UTC, shahbaz-successive commented on src/assignment-6/Ques1/Ques1.jsx
> +function Ques1() {
User should navigate to page when clicked home or about section. So try to implement a navigation to separate page.

2023-11-13 02:13 UTC, shahbaz-successive commented on src/assignment-6/Ques2/Ques2.jsx
> +const Ques2 = () => (
Once question 1 navigation is resolved update this too accordingly

2023-11-13 02:14 UTC, shahbaz-successive commented on src/assignment-6/Ques2/Ques2.jsx
> +    const componentDidCatch = (error) => {
This is unused code

2023-11-13 02:18 UTC, shahbaz-successive commented on src/assignment-6/Ques3/Ques3.test.js
> +test('increment btn click so count = count + 1', () => {
Test cases not running on my system, is it working on yours?

2023-11-13 02:20 UTC, shahbaz-successive commented on src/assignment-6/Ques4/Ques4.test.js
> +describe('Ques4', () => {
Check and run all test cases as it's not working on my system. Check for Ques5 and 6 as well.

2023-11-13 02:20 UTC, shahbaz-successive requested changes
Feedback changes

2023-11-14 10:30 UTC, nikhil1-successive commented on src/assignment-6/Ques3/Ques3.test.js
> +test('increment btn click so count = count + 1', () => {
Yes it is working.

2023-11-14 11:01 UTC, nikhil1-successive commented on src/assignment-6/Ques1/Ques1.jsx
> +function Ques1() {
done

2023-11-14 11:02 UTC, nikhil1-successive commented on src/assignment-6/Ques2/Ques2.jsx
> +const Ques2 = () => (
done

2023-11-14 11:02 UTC, nikhil1-successive commented on src/assignment-6/Ques2/Ques2.jsx
> +    const componentDidCatch = (error) => {
done

2023-11-14 11:02 UTC, nikhil1-successive commented on src/assignment-6/Ques4/Ques4.test.js
> +describe('Ques4', () => {
done

2023-11-16 05:48 UTC, shahbaz-successive approved these changes
👍

2023-11-16 05:48 UTC, merged